name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust the branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t product-transactions-dashboard .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.OUR_GITHUB_TOKEN }}

      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker tag product-transactions-dashboard ghcr.io/${{ github.repository_owner }}/product-transactions-dashboard:latest
          docker push ghcr.io/${{ github.repository_owner }}/product-transactions-dashboard:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
        env:
          GITHUB_TOKEN: ${{ secrets.OUR_GITHUB_TOKEN }} 